# Deployment database.yml
login: &login
  adapter: mysql2
  username: mmrdev
  password: g6xrKYDCQ4
  socket: /var/run/mysqld/mysqld.sock

production:
  database: mmrdev
  <<: *login

development:
  database: mmrtest
  <<: *login

staging:
  database: mmrdev
  <<: *login
