#  ON BLUEHOST
 development:
   adapter: mysql
   database: musical9_registration
   username: musical9_rails
   password: walla2
   socket: /tmp/mysql.sock

#development:
#   adapter: mysql
#   database: musical9_registration
#   username: musical9_rails
#   password: walla2
#   socket: /tmp/mysql.sock

# LOCALLY 
#development:
#  adapter: mysql
#  database: registration_development
#  username: root
#  password: 
#
#test:
#  adapter: mysql
#  database: registration_development
#  username: root
#  password: 
#
