#development:
#  login: 'jtrayn_1260315119_biz_api1.gmail.com'
#  password: '1260315126'
#  signature: 'AHwZ7.nXECbV1FrtA7HZEd4VDO71ADPSvlTHDOH5Wvovf1Lk5y4cJkw0'

#  Note, this is still test env
:
  login: 'seller_1261683294_biz@pobox.com'
  password: '1261683300'
  signature: 'AiPC9BjkCyDFQXbSkoZcgqH3hpacAkVoSpwBcKl7Aww-ZrvvcFj5BOv1'

test:
  login: 'seller_1261683294_biz@pobox.com'
  password: '1261683300'
  signature: 'AiPC9BjkCyDFQXbSkoZcgqH3hpacAkVoSpwBcKl7Aww-ZrvvcFj5BOv1'
